name: 'Linting'
description: 'Lint Python code with pre-commit'
inputs:
  python-version:
    required: false
    description: 'Which Python version to install'
    default: '3.9'
  pre-commit-cache-key:
    required: false
    description: 'The cache index. Should be indented to reset cache.'
    default: 'pre-commit-0'
outputs: {}
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.python-version }}

    - uses: actions/cache@v2
      id: cache-venv
      with:
        path: .venv
        key: venv-${{ inputs.pre-commit-cache-key }}

    - run: |
        if echo ${{ steps.cache-venv.outputs.cache-hit }} | grep -c "true"
        then
          echo "Cache hit - skipping dependency installation"
        else
          pip install virtualenv
          virtualenv .venv
          source .venv/bin/activate
          pip install pip setuptools wheel -U
          pip install pre-commit
        fi
      shell: bash

    - uses: actions/cache@v2
      id: cache-pre-commit-cache
      with:
        path: ~/.cache/pre-commit
        key: key-${{ inputs.pre-commit-cache-key }}

    - name: Run pre-commit
      run: pre-commit run --all-files
      shell: bash
